export const COMPANY_INFO = {
  name: "RHONEA Peinture",
  slogan: "Votre artisan peintre de confiance dans le Rhone",
  phone: "06 12 34 56 78",
  phoneFormatted: "+33612345678",
  email: "contact@rhonea-peinture.fr",
  address: "12 rue des Artisans",
  city: "Lyon",
  postalCode: "69000",
  region: "Rhone",
  yearsExperience: 12,
  projectsCompleted: 480,
  siret: "912 345 678 00019",
  insurance: {
    company: "AXA Assurances",
    contract: "DEC-4587962",
  },
  googleRating: 4.9,
  socialMedia: {
    facebook: "https://facebook.com/rhonea-peinture",
    instagram: "https://instagram.com/rhonea-peinture",
    linkedin: "https://linkedin.com/company/rhonea-peinture",
  },
  hours: {
    weekdays: "8h00 - 18h00",
    saturday: "9h00 - 12h00",
    sunday: "Ferme",
  },
};

export const NAVIGATION_ITEMS = [
  { label: "Accueil", href: "/" },
  { label: "Services", href: "/services" },
  { label: "Realisations", href: "/realisations" },
  { label: "Simulateur", href: "/simulateur" },
  { label: "A propos", href: "/a-propos" },
  { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
];

export const SERVICES = [
  {
    id: "peinture-interieure",
    title: "Peinture interieure",
    shortDescription: "Murs, plafonds, boiseries et radiateurs pour un interieur impeccable.",
    icon: "PaintBucket",
    href: "/services#peinture-interieure",
  },
  {
    id: "peinture-exterieure",
    title: "Peinture exterieure",
    shortDescription: "Facades, volets, portails et clotures pour sublimer votre exterieur.",
    icon: "Home",
    href: "/services#peinture-exterieure",
  },
  {
    id: "ravalement-facade",
    title: "Ravalement de facade",
    shortDescription: "Diagnostic, traitement et finition pour une facade comme neuve.",
    icon: "Building2",
    href: "/services#ravalement-facade",
  },
  {
    id: "revetements-muraux",
    title: "Revetements muraux",
    shortDescription: "Papier peint, toile de verre et crepi pour des murs uniques.",
    icon: "Wallpaper",
    href: "/services#revetements-muraux",
  },
  {
    id: "finitions-decoratives",
    title: "Finitions decoratives",
    shortDescription: "Effets, patines et stucco pour une touche d'elegance.",
    icon: "Sparkles",
    href: "/services#finitions-decoratives",
  },
  {
    id: "conseil-couleurs",
    title: "Conseil couleurs",
    shortDescription: "Accompagnement personnalise pour choisir vos couleurs ideales.",
    icon: "Palette",
    href: "/services#conseil-couleurs",
  },
];

export const CITIES = [
  { name: "Lyon", slug: "peintre-lyon", population: "520000" },
  { name: "Villeurbanne", slug: "peintre-villeurbanne", population: "150000" },
  { name: "Venissieux", slug: "peintre-venissieux", population: "65000" },
  { name: "Caluire-et-Cuire", slug: "peintre-caluire", population: "43000" },
  { name: "Bron", slug: "peintre-bron", population: "42000" },
  { name: "Saint-Priest", slug: "peintre-saint-priest", population: "47000" },
  { name: "Vaulx-en-Velin", slug: "peintre-vaulx-en-velin", population: "52000" },
  { name: "Meyzieu", slug: "peintre-meyzieu", population: "34000" },
  { name: "Rillieux-la-Pape", slug: "peintre-rillieux-la-pape", population: "31000" },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Marie Dupont",
    city: "Lyon 6eme",
    rating: 5,
    text: "Travail remarquable ! L'equipe de RHONEA a completement transforme notre appartement. Tres professionnels, ponctuels et soigneux. Je recommande vivement.",
    initials: "MD",
  },
  {
    id: 2,
    name: "Pierre Martin",
    city: "Villeurbanne",
    rating: 5,
    text: "Excellent rapport qualite-prix. Le ravalement de notre facade a ete realise dans les delais avec un resultat impeccable. Merci a toute l'equipe !",
    initials: "PM",
  },
  {
    id: 3,
    name: "Sophie Laurent",
    city: "Caluire",
    rating: 5,
    text: "Tres satisfaite de la peinture de mes 4 chambres. Les conseils couleurs etaient precieux et le rendu final est magnifique.",
    initials: "SL",
  },
  {
    id: 4,
    name: "Jean Dubois",
    city: "Bron",
    rating: 4,
    text: "Bon travail dans l'ensemble. Quelques retouches ont ete necessaires mais l'equipe est revenue rapidement pour les effectuer.",
    initials: "JD",
  },
  {
    id: 5,
    name: "Catherine Bernard",
    city: "Lyon 3eme",
    rating: 5,
    text: "Deuxieme fois que je fais appel a RHONEA. Toujours aussi satisfaite. Professionnalisme et qualite au rendez-vous !",
    initials: "CB",
  },
];

export const PROJECTS = [
  {
    id: 1,
    title: "Appartement haussmannien",
    type: "Interieur",
    city: "Lyon 6eme",
    surface: "120 m2",
    duration: "2 semaines",
    description: "Renovation complete d'un appartement haussmannien avec moulures et parquet.",
    imageBefore: "/images/projects/project1-before.jpg",
    imageAfter: "/images/projects/project1-after.jpg",
  },
  {
    id: 2,
    title: "Villa contemporaine",
    type: "Exterieur",
    city: "Caluire",
    surface: "250 m2",
    duration: "3 semaines",
    description: "Peinture exterieure complete d'une villa moderne avec finition satinee.",
    imageBefore: "/images/projects/project2-before.jpg",
    imageAfter: "/images/projects/project2-after.jpg",
  },
  {
    id: 3,
    title: "Immeuble Annees 70",
    type: "Facade",
    city: "Villeurbanne",
    surface: "800 m2",
    duration: "6 semaines",
    description: "Ravalement complet avec isolation thermique par l'exterieur.",
    imageBefore: "/images/projects/project3-before.jpg",
    imageAfter: "/images/projects/project3-after.jpg",
  },
  {
    id: 4,
    title: "Bureaux startup",
    type: "Professionnel",
    city: "Lyon Part-Dieu",
    surface: "300 m2",
    duration: "10 jours",
    description: "Amenagement et peinture de bureaux open-space avec zones colorees.",
    imageBefore: "/images/projects/project4-before.jpg",
    imageAfter: "/images/projects/project4-after.jpg",
  },
  {
    id: 5,
    title: "Maison de ville",
    type: "Interieur",
    city: "Bron",
    surface: "90 m2",
    duration: "1 semaine",
    description: "Rafraichissement complet d'une maison de ville sur 2 etages.",
    imageBefore: "/images/projects/project5-before.jpg",
    imageAfter: "/images/projects/project5-after.jpg",
  },
  {
    id: 6,
    title: "Restaurant gastronomique",
    type: "Professionnel",
    city: "Lyon Presqu'ile",
    surface: "150 m2",
    duration: "2 semaines",
    description: "Peinture decorative avec effets patines pour une ambiance chaleureuse.",
    imageBefore: "/images/projects/project6-before.jpg",
    imageAfter: "/images/projects/project6-after.jpg",
  },
  {
    id: 7,
    title: "Pavillon familial",
    type: "Exterieur",
    city: "Meyzieu",
    surface: "180 m2",
    duration: "2 semaines",
    description: "Renovation des facades et volets d'un pavillon des annees 80.",
    imageBefore: "/images/projects/project7-before.jpg",
    imageAfter: "/images/projects/project7-after.jpg",
  },
  {
    id: 8,
    title: "Loft industriel",
    type: "Interieur",
    city: "Lyon 7eme",
    surface: "200 m2",
    duration: "3 semaines",
    description: "Mise en peinture d'un loft avec plafonds hauts et poutres metalliques.",
    imageBefore: "/images/projects/project8-before.jpg",
    imageAfter: "/images/projects/project8-after.jpg",
  },
  {
    id: 9,
    title: "Residence collective",
    type: "Facade",
    city: "Saint-Priest",
    surface: "1200 m2",
    duration: "8 semaines",
    description: "Ravalement de facade d'une residence de 24 logements.",
    imageBefore: "/images/projects/project9-before.jpg",
    imageAfter: "/images/projects/project9-after.jpg",
  },
  {
    id: 10,
    title: "Boutique mode",
    type: "Professionnel",
    city: "Lyon 2eme",
    surface: "80 m2",
    duration: "1 semaine",
    description: "Peinture et finitions pour une boutique de pret-a-porter haut de gamme.",
    imageBefore: "/images/projects/project10-before.jpg",
    imageAfter: "/images/projects/project10-after.jpg",
  },
  {
    id: 11,
    title: "Maison bourgeoise",
    type: "Interieur",
    city: "Lyon 4eme",
    surface: "280 m2",
    duration: "4 semaines",
    description: "Renovation complete avec restauration des elements decoratifs d'epoque.",
    imageBefore: "/images/projects/project11-before.jpg",
    imageAfter: "/images/projects/project11-after.jpg",
  },
  {
    id: 12,
    title: "Local commercial",
    type: "Professionnel",
    city: "Vaulx-en-Velin",
    surface: "400 m2",
    duration: "3 semaines",
    description: "Peinture sol et murs d'un entrepot transforme en showroom.",
    imageBefore: "/images/projects/project12-before.jpg",
    imageAfter: "/images/projects/project12-after.jpg",
  },
];
