export const COMPANY_INFO = {
  name: "RHONEA Peinture",
  slogan: "Votre artisan peintre de confiance dans le Rhône",
  phone: "06 12 34 56 78",
  phoneFormatted: "+33612345678",
  email: "contact@rhonea-peinture.fr",
  address: "12 rue des Artisans",
  city: "Lyon",
  postalCode: "69000",
  region: "Rhône",
  yearsExperience: 12,
  projectsCompleted: 480,
  siret: "912 345 678 00019",
  insurance: {
    company: "AXA Assurances",
    contract: "DEC-4587962",
  },
  googleRating: 4.9,
  socialMedia: {
    facebook: "https://facebook.com/rhonea-peinture",
    instagram: "https://instagram.com/rhonea-peinture",
    linkedin: "https://linkedin.com/company/rhonea-peinture",
  },
  hours: {
    weekdays: "8h00 - 18h00",
    saturday: "9h00 - 12h00",
    sunday: "Fermé",
  },
};

export const NAVIGATION_ITEMS = [
  { label: "Accueil", href: "/" },
  { label: "Services", href: "/services" },
  { label: "Réalisations", href: "/realisations" },
  { label: "Simulateur", href: "/simulateur" },
  { label: "À propos", href: "/a-propos" },
  { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
];

export const SERVICES = [
  {
    id: "peinture-interieure",
    title: "Peinture intérieure",
    shortDescription:
      "Murs, plafonds, boiseries et radiateurs pour un intérieur impeccable.",
    icon: "PaintBucket",
    href: "/services#peinture-interieure",
  },
  {
    id: "peinture-exterieure",
    title: "Peinture extérieure",
    shortDescription:
      "Façades, volets, portails et clôtures pour sublimer votre extérieur.",
    icon: "Home",
    href: "/services#peinture-exterieure",
  },
  {
    id: "ravalement-facade",
    title: "Ravalement de façade",
    shortDescription: "Diagnostic, traitement et finition pour une façade comme neuve.",
    icon: "Building2",
    href: "/services#ravalement-facade",
  },
  {
    id: "revetements-muraux",
    title: "Revêtements muraux",
    shortDescription: "Papier peint, toile de verre et crépi pour des murs uniques.",
    icon: "Wallpaper",
    href: "/services#revetements-muraux",
  },
  {
    id: "finitions-decoratives",
    title: "Finitions décoratives",
    shortDescription: "Effets, patines et stucco pour une touche d'élégance.",
    icon: "Sparkles",
    href: "/services#finitions-decoratives",
  },
  {
    id: "conseil-couleurs",
    title: "Conseil couleurs",
    shortDescription: "Accompagnement personnalisé pour choisir vos couleurs idéales.",
    icon: "Palette",
    href: "/services#conseil-couleurs",
  },
];

export const CITIES = [
  { name: "Lyon", slug: "peintre-lyon", population: "520000" },
  { name: "Villeurbanne", slug: "peintre-villeurbanne", population: "150000" },
  { name: "Vénissieux", slug: "peintre-venissieux", population: "65000" },
  { name: "Caluire-et-Cuire", slug: "peintre-caluire", population: "43000" },
  { name: "Bron", slug: "peintre-bron", population: "42000" },
  { name: "Saint-Priest", slug: "peintre-saint-priest", population: "47000" },
  { name: "Vaulx-en-Velin", slug: "peintre-vaulx-en-velin", population: "52000" },
  { name: "Meyzieu", slug: "peintre-meyzieu", population: "34000" },
  { name: "Rillieux-la-Pape", slug: "peintre-rillieux-la-pape", population: "31000" },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Marie Dupont",
    city: "Lyon 6ème",
    rating: 5,
    text: "Travail remarquable ! L'équipe de RHONEA a complètement transformé notre appartement. Très professionnels, ponctuels et soigneux. Je recommande vivement.",
    initials: "MD",
  },
  {
    id: 2,
    name: "Pierre Martin",
    city: "Villeurbanne",
    rating: 5,
    text: "Excellent rapport qualité-prix. Le ravalement de notre façade a été réalisé dans les délais avec un résultat impeccable. Merci à toute l'équipe !",
    initials: "PM",
  },
  {
    id: 3,
    name: "Sophie Laurent",
    city: "Caluire",
    rating: 5,
    text: "Très satisfaite de la peinture de mes 4 chambres. Les conseils couleurs étaient précieux et le rendu final est magnifique.",
    initials: "SL",
  },
  {
    id: 4,
    name: "Jean Dubois",
    city: "Bron",
    rating: 4,
    text: "Bon travail dans l'ensemble. Quelques retouches ont été nécessaires mais l'équipe est revenue rapidement pour les effectuer.",
    initials: "JD",
  },
  {
    id: 5,
    name: "Catherine Bernard",
    city: "Lyon 3ème",
    rating: 5,
    text: "Deuxième fois que je fais appel à RHONEA. Toujours aussi satisfaite. Professionnalisme et qualité au rendez-vous !",
    initials: "CB",
  },
];

export const PROJECTS = [
  {
    id: 1,
    title: "Appartement haussmannien",
    type: "Intérieur",
    city: "Lyon 6ème",
    surface: "120 m2",
    duration: "2 semaines",
    description: "Rénovation complète d'un appartement haussmannien avec moulures et parquet.",
    imageBefore: "/images/projects/project1-before.jpg",
    imageAfter: "/images/projects/project1-after.jpg",
  },
  {
    id: 2,
    title: "Villa contemporaine",
    type: "Extérieur",
    city: "Caluire",
    surface: "250 m2",
    duration: "3 semaines",
    description: "Peinture extérieure complète d'une villa moderne avec finition satinée.",
    imageBefore: "/images/projects/project2-before.jpg",
    imageAfter: "/images/projects/project2-after.jpg",
  },
  {
    id: 3,
    title: "Immeuble Années 70",
    type: "Façade",
    city: "Villeurbanne",
    surface: "800 m2",
    duration: "6 semaines",
    description: "Ravalement complet avec isolation thermique par l'extérieur.",
    imageBefore: "/images/projects/project3-before.jpg",
    imageAfter: "/images/projects/project3-after.jpg",
  },
  {
    id: 4,
    title: "Bureaux startup",
    type: "Professionnel",
    city: "Lyon Part-Dieu",
    surface: "300 m2",
    duration: "10 jours",
    description: "Aménagement et peinture de bureaux open-space avec zones colorées.",
    imageBefore: "/images/projects/project4-before.jpg",
    imageAfter: "/images/projects/project4-after.jpg",
  },
  {
    id: 5,
    title: "Maison de ville",
    type: "Intérieur",
    city: "Bron",
    surface: "90 m2",
    duration: "1 semaine",
    description: "Rafraîchissement complet d'une maison de ville sur 2 étages.",
    imageBefore: "/images/projects/project5-before.jpg",
    imageAfter: "/images/projects/project5-after.jpg",
  },
  {
    id: 6,
    title: "Restaurant gastronomique",
    type: "Professionnel",
    city: "Lyon Presqu'île",
    surface: "150 m2",
    duration: "2 semaines",
    description: "Peinture décorative avec effets patinés pour une ambiance chaleureuse.",
    imageBefore: "/images/projects/project6-before.jpg",
    imageAfter: "/images/projects/project6-after.jpg",
  },
  {
    id: 7,
    title: "Pavillon familial",
    type: "Extérieur",
    city: "Meyzieu",
    surface: "180 m2",
    duration: "2 semaines",
    description: "Rénovation des façades et volets d'un pavillon des années 80.",
    imageBefore: "/images/projects/project7-before.jpg",
    imageAfter: "/images/projects/project7-after.jpg",
  },
  {
    id: 8,
    title: "Loft industriel",
    type: "Intérieur",
    city: "Lyon 7ème",
    surface: "200 m2",
    duration: "3 semaines",
    description: "Mise en peinture d'un loft avec plafonds hauts et poutres métalliques.",
    imageBefore: "/images/projects/project8-before.jpg",
    imageAfter: "/images/projects/project8-after.jpg",
  },
  {
    id: 9,
    title: "Résidence collective",
    type: "Façade",
    city: "Saint-Priest",
    surface: "1200 m2",
    duration: "8 semaines",
    description: "Ravalement de façade d'une résidence de 24 logements.",
    imageBefore: "/images/projects/project9-before.jpg",
    imageAfter: "/images/projects/project9-after.jpg",
  },
  {
    id: 10,
    title: "Boutique mode",
    type: "Professionnel",
    city: "Lyon 2ème",
    surface: "80 m2",
    duration: "1 semaine",
    description: "Peinture et finitions pour une boutique de prêt-à-porter haut de gamme.",
    imageBefore: "/images/projects/project10-before.jpg",
    imageAfter: "/images/projects/project10-after.jpg",
  },
  {
    id: 11,
    title: "Maison bourgeoise",
    type: "Intérieur",
    city: "Lyon 4ème",
    surface: "280 m2",
    duration: "4 semaines",
    description: "Rénovation complète avec restauration des éléments décoratifs d'époque.",
    imageBefore: "/images/projects/project11-before.jpg",
    imageAfter: "/images/projects/project11-after.jpg",
  },
  {
    id: 12,
    title: "Local commercial",
    type: "Professionnel",
    city: "Vaulx-en-Velin",
    surface: "400 m2",
    duration: "3 semaines",
    description: "Peinture sol et murs d'un entrepôt transformé en showroom.",
    imageBefore: "/images/projects/project12-before.jpg",
    imageAfter: "/images/projects/project12-after.jpg",
  },
];
